### ISSUE TITLE
Can't check in - "Detecting location"

### ISSUE THREAD

**Issue by allsabotage** [velazcod/Tinfoil-Facebook#48]
I'm having trouble getting the check in feature to work. I've enabled it in Permissions.

I can check in without a problem through either of the web browsers on my phone (Chrome and Firefox), but in Tinfoil it just stays on "Detecting location".

I've tried uninstalling and reinstalling the app, disabling and renabling check ins and location services, but Tinfoil still cannot detect my location.

I'm using a 1st-gen Moto G running 4.4.4

**Comment by allsabotage** [comment]
Nexus 7 now updated to 5.0.2 and the problem persists. And still having the same problem on my Moto G. Is there a log or something I can access that might point to the problem?

**Comment by velazcod** [comment]
I was just looking into this, and you are correct, geolocation no longer works. This seems to be a bug with the WebView, actually, 2. One is that the FINE_LOCATION permission is now needed for it to work, which is not ideal, using just COARSE_LOCATION doesn't work anymore.

The other issue is that the WebView is no longer making a call to the implementation to ask if geolocation can be used, which is also not ideal for privacy issues.

I will look into this a bit more and keep this updated.
