### ISSUE TITLE
Fix for image scaling issue on small screens

### ISSUE THREAD

**Issue by easyaspi314** [velazcod/Tinfoil-Facebook#49]
On small screens, there is an issue where some images are too large, causing them to go off-screen. There is a fix, add this to your WebView code:
```java
webView.getSettings().setLoadWithOverviewMode(true);
webView.getSettings().setUseWideViewPort(true);
```
I didn't really want to make a PR for such a tiny change.

**Comment by velazcod** [comment]
I made this change with commit c1530f3838921ece2af2ca8b7f3f4aa48c9c6ff5

thanks!

**Comment by jpchow26** [comment]
I'm using 1.7.5 on a Nexus 4 and I'm still seeing images clipped by the right edge

**Comment by mxmehl** [comment]
Same as @jpchow26 here with Galaxy Nexus (Cyanogenmod 11, Android 4.4.4)

**Comment by jpchow26** [comment]
Magically started working properly again... Perhaps a change in Facebook...?

**Comment by velazcod** [comment]
Yes, this issue has always been a problem on Facebook's side, and the behavior changes depending on the browser you use due to their A/B testing mechanism, so there isn't much I can do to fix things permanently.

**Comment by easyaspi314** [comment]
Yet [this](https://gist.github.com/easyaspi314/aaffea99461139077389) works. Weird.
