### ISSUE TITLE
Keyboard hides input field - very anoying! 

### ISSUE THREAD

**Issue by Enkidu70** [velazcod/Tinfoil-Facebook#58]
E.g. when I want to comment something and input field is in bottom 1/3 of my display, keyboard opens over input field! 

This is very anoying because I do not see what I write! And I have no real workaround. Except switching to desktop mode. 

TF is the only app doing like this. Opening FB in browser works very fine. 

Android 4.4.4 CM11 on OnePlus One

**Comment by velazcod** [comment]
This is an issue on the mobile site, there isn't much I can do, the reason why it acts different on Tinfoil vs a different browser is because Facebook uses different configurations for testing between different  browsers, sorry.
