### ISSUE TITLE
Notifications no longer work/Menu missing options

### ISSUE THREAD

**Issue by Catalinawinemixer** [velazcod/Tinfoil-Facebook#76]
When selecting to view any of my notifications receive message that says "Sorry, we got confused
Please try refreshing the page or closing and re-opening your browser window.", therefore I cannot view any notifications. Additionally, when clicking the hamburger menu, can no longer see any Facebook apps (ie "On This Day") These are both tinfoil only issues, as they do not happen when on Facebook Mobile site using my phone's browser. Running Android 6.0.1

**Comment by jfmcbrayer** [comment]
Does refreshing the page help with this? I can't reproduce this on 4.4.4 or 5.1.1.

**Comment by Catalinawinemixer** [comment]
Unfortunately no, it still happens. It started right when I updated to
6.0.1 security patch level 1/1/16
I attached a screenshot to this email so you can see the error message I'm
getting.
Thanks for the quick reply.

**Comment by Catalinawinemixer** [comment]
Hi, me again. I figured out the issue, somehow I was using Tinfoil as a
Page that I manage. Not sure how that happened, I was still getting my
personal notifications, but once I figured it out and switched back,
everything worked again

**Comment by velazcod** [comment]
OK cool, thanks for letting us know about it.
