### ISSUE TITLE
App crashes accessing messages.

### ISSUE THREAD

**Issue by wolf6243** [velazcod/Tinfoil-Facebook#83]
App crashes every time I try to access my messages in Facebook, only started today.

**Comment by jcassano** [comment]
Also having the same issue. Started at the same time.

Not sure if it's related, but I saw it shortly after a notice from Facebook saying soon messages would only be accessible inside the messenger app.

**Comment by mikebabb** [comment]
Appears to be related to a push for users to install the native Messenger app. There [may be a workaround](https://github.com/velazcod/Tinfoil-Facebook/issues/84#issuecomment-211286474) Tinfoil devs can use to keep messaging relatively well integrated.

**Comment by miiichael** [comment]
I do notice that switching to ”desktop” version is also a (inconvenient) workaround.

**Comment by abdullahhhhh** [comment]
Only the Desktop or Basic versions work. The rest crash :/

**Comment by andoks** [comment]
Same here, crashed egen i try to use the messenger functionality

**Comment by abrugsch** [comment]
Workaround! 
in preferences select "open links inside app" 
this makes the browser intent redirect to the app,  but the web view doesn't know what to do with it so just displays a web error page. clicking back takes you to the messages. still annoying but it works...  (for now)

**Comment by miiichael** [comment]
Workaround doesn't work for me. :disappointed: 

Hitting Back takes me back to where I was before tapping on Messages.

**Comment by gsurrel** [comment]
I've created a small dumb app to prevent Tinfoil from crashing because of that. If you are interested, it's here:
https://github.com/gsurrel/MessengerBypasser

Basically, it reacts to the same events as Messenger so it opens without crashing, but immediately quits itself to return to Tinfoil.

**Comment by hovancik** [comment]
@gsurrel how do I set it up? Does nothing for me...

**Comment by jgkamat** [comment]
@hovancik I just installed it via the apk in the readme and it seemed to just work. Thanks @gsurrel, btw!

**Comment by hovancik** [comment]
@gsurrel @jgkamat it's not doing anything for me.

**Comment by omegaplatinum** [comment]
I figured out the probable cause of the issue. When you access the mobile facebook site on chrome, for example, hitting the message button, in addition to opening up your messages, pops up Messenger's page on the Google Play store. Never thought I'd have to deal with pop ups on Facebook of all websites. The open links in app work around worked for me, but is there a way to stop the redirect all together?

**Comment by robyf** [comment]
The workaround doesn't work for me either, when I hit back from the error page I go back to the page I was, not to the messages one. The only thing that worked so far was to force the site to basic.

**Comment by gsurrel** [comment]
@hovancik There shouldn't be any set-up required and it shouldn't have any visible action (the app quits immediately after having been started). It just pretends to be the Messenger app by handling the "Open Messenger" links.

@omegaplatinum  This issue [has been opened by someone else](https://github.com/gsurrel/MessengerBypasser/issues/3) and I tried to catch also that but without success up to now. I have problems filtering the "Open Play Store" intents : when using the `https://` link, the store *always* opens and I have no idea why. When using `market://`, I couldn't find a way to filter only the Messenger app. I'm sure the latter problem can be fixed, though.

@robyf Which browser are you using? Is it Tinfoil for Facebook or something else (Chrome, Firefox…)

**Comment by robyf** [comment]
I guess I should have been more specific :) The workaround I tried was the one described by abrugsch: to set the "open links inside app" preference, so the browser I was using at the time was Tinfoil for Facebook.

**Comment by jeancayron** [comment]
The workaround (MessengerBypasser) worked great for me.
It should included as dependency of Tinfoil if possible.
Note that the bug does not appear in Firefox (maybe want messenger does not exist in Firefox OS? [RIP])

**Comment by vivia** [comment]
This worked for me too a few days ago. Now it just doesn't crash, but I cannot find a way to access the messages. I only get the "please install messenger" nag screen. Anyone else with the same issue?

**Comment by gsurrel** [comment]
@vivia Indeed, I got the same behavior on my side from Facebook. The only way I could get back a web messenger is to use another browser than tinfoil with the following user agent:

    Mozilla/5.0 (Linux; U; Android 2.3; en-us; Nexus 4 Build/JOP24G) AppleWebKit/534.30 (KHTML, like Gecko) 

The important part being announcing Android 2.3 as I guess it's too old to be supported by Messenger and therefore allowing web access to messages. The best would be to have tinfoil declare that user-agent.

**Comment by jfmcbrayer** [comment]
It might be a good idea only to send that user-agent string when requesting the messages page, because who knows what other things Facebook might assume about the browser.

**Comment by donutz** [comment]
What about making the Messages link in the right-side menu send you to https://mbasic.facebook.com/messages/ , would that be a good workaround so we don't need the messenger app to view messages?

**Comment by zieglarnatta** [comment]
For now if you temporarily move it to Facebook basic mode, you can read & write messages. I am using FB mini for messages but I despise the ads that mini serves up.

**Comment by hovancik** [comment]
I am using Toffeed (https://github.com/JakeLane/Toffeed), messages work there
