### ISSUE TITLE
Messages no longer work

### ISSUE THREAD

**Issue by jgkamat** [velazcod/Tinfoil-Facebook#87]
Today, I got a message about switching to messenger in the chat column of tinfoil browser, and when I closed that message, tinfoil browser crashed. I'm not sure how to produce debug logs though, and I wanted to see if anyone else is seeing this as well. I think this is related to a change fb pushed today.

**Comment by abrugsch** [comment]
facebook is trying to force open the messenger app im the play store on the mobile site. this causes tinfoil to crash

**Comment by abrugsch** [comment]
it happens on any interactiom with the mobile web messeges page. *SUPER* agressive

**Comment by jgkamat** [comment]
Hopefully there's a way to block these requests, they are really, really annoying. It might be possible that facebook made it impossible to message on mobile, (but it should be possible to trick it by changing the user agent, perhaps?)

**Comment by kofalt** [comment]
Relevant discussion on r/privacy: https://www.reddit.com/r/privacy/comments/4m1whp/facebook_is_trying_to_force_messenger_download_by/

Among the comments are folks wondering if a user agent change would be enough to fix the crash.

**Comment by jgkamat** [comment]
This is a dupe of #83 and #84, closing this to try to centralize discussion.
