### ISSUE TITLE
v1.7.6 missing in F-Droid Store

### ISSUE THREAD

**Issue by Krawei** [velazcod/Tinfoil-Facebook#98]
When I take a look in the playstore I notice, that "Tinfoil for Facebook's" current version is v1.7.6. In the F-Droid store the current version is v1.7. 5

What's the reason for the different versions? Is this Github-project still alive?

Kind Regards,

Krawei

**Comment by jfmcbrayer** [comment]
v1.7.6 was just released in the last couple of days. I assume F-Droid has not pulled and rebuilt it from the latest sources. You can see the 1.7.6 release tag here on GitHub.

**Comment by kofalt** [comment]
Just an update - this is still missing.

**Comment by danny316p** [comment]
I see both v.1.7.6 and v.1.7.7 in F-Droid now...

**Comment by Krawei** [comment]
Current version available in f-droid. Issue is solved.
